# Generated by Django 5.0.3 on 2024-03-20 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Категори',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название склада')),
                ('location', models.CharField(max_length=100, verbose_name='Расположение')),
                ('capacity', models.IntegerField(verbose_name='Объем')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество единиц товара')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('characteristic', models.TextField(blank=True, verbose_name='Характеристика')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse_management.category', verbose_name='Категория')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.warehouse', verbose_name='На каком складе находится')),
            ],
            options={
                'verbose_name': 'Единица инвентаря',
                'verbose_name_plural': 'Единицы инвентаря',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('date_produced', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата производства')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.inventoryitem', verbose_name='Название производства')),
            ],
            options={
                'verbose_name': 'Производство',
                'verbose_name_plural': 'Производства',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='количество товаров')),
                ('date_moved', models.DateTimeField(default=django.utils.timezone.now)),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse_management.inventoryitem', verbose_name='Инвентарь')),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_location', to='warehouse_management.warehouse')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_location', to='warehouse_management.warehouse')),
            ],
        ),
    ]
